# Site settings
title: colmarius
name: Marius Colacioiu
profession: Software Engineer
email: hello@colmarius.net
description: "This is my personal website were you can learn more about me."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Marius Colacioiu
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/colmarius
  - title: twitter
    url: http://twitter.com/colmarius
  - title: linkedin
    url: https://www.linkedin.com/in/mariuscolacioiu
  - title: book
    url: https://www.goodreads.com/colmarius

# Postal address (add as many lines as necessary)
address:
  - line: ZÃ¼rich, Switzerland

# Build settings
markdown: kramdown
permalink: pretty
